name: cu_showcase
description: CU UI Design Language Showcase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cu_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false

  assets:
    - assets/fonts/

  fonts:
    - family: Cyrovoid
      fonts:
        - asset: assets/fonts/Cyrovoid.ttf
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700
